### ISSUE TITLE
Unit tests failing on Python 3.5

### ISSUE THREAD

**Issue by jameswettenhall** [mytardis/mytardis#2098]
Currently we test against Python v3.6 and v3.7, but it has been brought to our attention that MyTardis's unit tests fail when run against Python v3.5 with errors like this:

```
Traceback (most recent call last):
  File "/home/mytardis/mytardis/tardis/apps/openid_migration/tests/test_migration.py", line 67, in test_do_migration
    d = json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by jameswettenhall** [comment]
The relevant change in Python v3.6 is this: https://docs.python.org/3/whatsnew/3.6.html#json

> json.load() and json.loads() now support binary input. Encoded JSON should be represented using either UTF-8, UTF-16, or UTF-32. (Contributed by Serhiy Storchaka in bpo-17909.)


So to make MyTardis v4.1's unit tests compatible with Python 3.5, we would need to replace instances of `json.loads(response.content)` with `json.loads(response.content.decode())` or equivalent.
