### ISSUE TITLE
Downloading tar archives from Swift-backed MyTardis fails with AttributeError: StringIO instance has no attribute 'fileno'

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#351]
Traceback (most recent call last):

  File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/opt/mytardis/current/tardis/tardis_portal/download.py", line 503, in streaming_download_datafiles
    comptype, organization)

  File "/opt/mytardis/current/tardis/tardis_portal/download.py", line 370, in _streaming_downloader
    do_gzip=comptype != 'tar')

  File "/opt/mytardis/current/tardis/tardis_portal/download.py", line 219, in __init__
    self.tar_size = self.compute_size()

  File "/opt/mytardis/current/tardis/tardis_portal/download.py", line 226, in compute_size
    size = os.fstat(the_file.fileno()).st_size

  File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/files/utils.py", line 12, in <lambda>
    fileno = property(lambda self: self.file.fileno)

AttributeError: StringIO instance has no attribute 'fileno'

**Comment by grischa** [comment]
closed by PR #353
