### ISSUE TITLE
UserProfile should be created automatically when user record is created.

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#379]
If I create a localdb user account (in MyTardis's Django admin), and then try to log in as that account (without creating a UserProfile first), I get the following:

```
tardis.tardis_portal.models.access_control.DoesNotExist
DoesNotExist: UserProfile matching query does not exist.

Traceback (most recent call last)
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/handlers/wsgi.py", line 255, in __call__
response = self.get_response(request)
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/handlers/base.py", line 178, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/handlers/base.py", line 217, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/opt/mytardis/develop/eggs/django_extensions-1.1.1-py2.7.egg/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/core/handlers/base.py", line 115, in get_response
response = callback(request, *callback_args, **callback_kwargs)
File "/opt/mytardis/develop/tardis/tardis_portal/views.py", line 211, in index
private_experiments = Experiment.safe.owned_and_shared(request.user)\
File "/opt/mytardis/develop/tardis/tardis_portal/managers.py", line 74, in owned_and_shared
self._query_owned_and_shared(user)).distinct()
File "/opt/mytardis/develop/tardis/tardis_portal/managers.py", line 81, in _query_owned_and_shared
return self._query_shared(user) | self._query_owned(user)
File "/opt/mytardis/develop/tardis/tardis_portal/managers.py", line 117, in _query_shared
for name, group in user.get_profile().ext_groups:
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/contrib/auth/models.py", line 450, in get_profile
self._state.db).get(user__id__exact=self.id)
File "/opt/mytardis/develop/eggs/Django-1.5.5-py2.7.egg/django/db/models/query.py", line 404, in get
self.model._meta.object_name)
DoesNotExist: UserProfile matching query does not exist.
```

**Comment by grischa** [comment]
is automatic now
