### ISSUE TITLE
verify md5sum key error

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#452]
```
[2015-05-22 09:01:14,448: ERROR/MainProcess] Task tardis_portal.verify_dfo[1693f574-b5ef-4b68-8f39-3d5d35d50679] raised unexpected: KeyError('md5sum',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/mytardis/develop/tardis/tardis_portal/tasks.py", line 53, in verify_dfo
    dfo.verify()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 419, in __call__
    return self.run(self.__self__, *args, **kwargs)
  File "/opt/mytardis/develop/tardis/tardis_portal/models/datafile.py", line 590, in verify
    key, getattr(df, key), actual[key]))
KeyError: 'md5sum'
```

**Comment by grischa** [comment]
closed by https://github.com/mytardis/mytardis/commit/65a66f4
