### ISSUE TITLE
DataFile model's cache_file task's argument (self) is not easily pickleable

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#498]
Relevant methods:
- cache_dataset in tardis/tardis_portal/views.py
- cache_file in tardis/tardis_portal/models/datafile.py

```
Internal Server Error: /api/v1/dataset_file/114111/download/
Traceback (most recent call last):
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/middleware/cache.py", line 103, in process_response
    self.cache.set(cache_key, response, timeout)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/cache/backends/db.py", line 89, in set
    self._base_set('set', key, value, timeout)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/cache/backends/db.py", line 115, in _base_set
    pickled = pickle.dumps(value, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

Request repr():
<WSGIRequest
path:/api/v1/dataset_file/114111/download/,
```

**Comment by grischa** [comment]
It's an issue with the global cache. Turn off cache for this?

**Comment by wettenhj** [comment]
I've disabled the cache middleware as a temporary workaround which fixes the problem for now.  But I would like to be able to enable caching if possible.

**Comment by grischa** [comment]
I meant add the `@never_cache` decorator to this method/view

**Comment by wettenhj** [comment]
The cache_dataset view already has the ```@never_cache``` decorator:
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/views.py#L1015

The cache_file method doesn't, but it is not a view, just a task, so I don't think it needs it:
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L103

I think this code in cache_dataset is problematic, because it is run with apply_async, but doesn't use  easily pickleable arguments:
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/views.py#L1019
```
    run_this = group(df.cache_file.s()
                     for df in dataset.datafile_set.all())
```

**Comment by grischa** [comment]
I thought this happens when it is trying to cache a file download, i.e. `/api/v1/dataset_file/114111/download/`. If file downloads in general are not cached, the problem should not occur. Am I missing something?

**Comment by wettenhj** [comment]
Hmm, I could have made some incorrect assumptions.  This might need more verbose logging.

**Comment by wettenhj** [comment]
OK, I think I understand what's going on a little better now, and I now think the title of the issue I created is completely misleading, so feel free to close it and maybe open a new one instead?  When I tried to download a datafile with caching middleware turned on, templates/tardis_portal/ajax/datafile_list.html requested datafile.get_download_url which returned '/api/v1/dataset_file/%d/download' % self.id, i.e. it's using TastyPie to respond to the datafile download request, and I don't think TastyPie supports Django's ```@never_cache```.
