### ISSUE TITLE
Missing bootstrap fonts when running collectstatic for push_to

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#502]
When I ran collectstatic after upgrading to the latest MyTardis (with push_to), I got errors about missing fonts:

```
Post-processing 'push-to/bootstrap/css/bootstrap.min.css' failed!

Traceback (most recent call last):
  File "mytardis.py", line 26, in <module>
    run()
  File "mytardis.py", line 20, in run
    execute_from_command_line(sys.argv)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'push-to/bootstrap/fonts/glyphicons-halflings-regular.eot' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7f3d79209d50>.
```

So I added the following, and then it worked:

```
push_to/static/push-to/bootstrap/fonts/glyphicons-halflings-regular.svg
push_to/static/push-to/bootstrap/fonts/glyphicons-halflings-regular.woff2
push_to/static/push-to/bootstrap/fonts/glyphicons-halflings-regular.ttf
push_to/static/push-to/bootstrap/fonts/glyphicons-halflings-regular.eot
push_to/static/push-to/bootstrap/fonts/glyphicons-halflings-regular.woff
```

See: https://github.com/jasonrig/mytardis/commit/20927877477532b3fe33e63fc244d147cbaeabb6

**Comment by jasonrig** [comment]
Temporary fix is to put the bootstrap fonts into the push-to app. There is a discussion on slack about this..  I'll PR something soon to address this more permanently

**Comment by wettenhj** [comment]
Hi @jasonrig , ah sorry I missed the Slack discussion - thanks for letting me know about it.  Yes, working around the problem is easy.

**Comment by grischa** [comment]
Can you add a test for running collectstatic as part of the PR, @jasonrig? That would be great!
You'd probably want to add a special static root destination folder in `test_settings.py` for this, too.

Some references: http://stackoverflow.com/questions/907506/how-can-i-call-a-custom-django-manage-py-command-directly-from-a-test-driver
https://docs.djangoproject.com/en/1.8/ref/django-admin/#running-management-commands-from-your-code
