### ISSUE TITLE
Unique together in UserAuthentication model would be nice to have

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#678]
In the UserAuthentication model, it would be nice to have a unique_together constraint for username, authenticationMethod: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/access_control.py#L93

Things work nicely when a user creates a MyTardis account for themselves by logging in for the first time with their LDAP credentials.

But in cases where User1 wants to add User2 to a facility managers group and User2 doesn't yet have an account on MyTardis, the UserAuthentication record for User2 needs to be create manually (by the MyTardis Admin), otherwise the first time user2 logs in with their LDAP credentials, they will see a "1" at the end of their username, indicating that MyTardis hasn't linked their LDAP account to the existing "user2" account created by the MyTardis admin using the default Django authentication method.

Given that the UserAuthentication record needs to be created manually in this case (e.g. via Django admin), without a "unique together" constraint, it's possible to accidentally create a duplicate UserAuthentication record (same username and same authentication method), resulting in:

```
Internal Server Error: /admin/tardis_portal/userauthentication/
Traceback (most recent call last):
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/template/context.py", line 241, in bind_template
    updates.update(processor(self.request))
  File "/home/mytardis/mytardis/tardis/tardis_portal/context_processors.py", line 51, in user_details_processor
    staging = True if get_full_staging_path(username) else False
  File "/home/mytardis/mytardis/tardis/tardis_portal/staging.py", line 177, in get_full_staging_path
    authenticationMethod=settings.STAGING_PROTOCOL)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one UserAuthentication -- it returned 2!
```

**Comment by nrmay** [comment]
Good idea. Should include this in https://github.com/mytardis/mytardis/issues/754
